### ISSUE TITLE
authorize-ios command failing *likely* after Xcode 9.1 install

### ISSUE THREAD

**Issue by radamstx** [appium/authorize-ios#14] opened 2017-11-14 18:41 UTC
Previously this command had worked for me and my teammates. One of my teammates identified that he was unable to run it successfully today. It is believed that after the Xcode 9.1 install, directory locations had changed for simulators and their dependent files, at least in comparison to the paths constructed in the `authorize.js`. I was able to run it previously and confirmed that now with Xcode 9.1, I'm no longer able to run it successfully.

My output:

```
info AuthorizeIOS Enabling DevToolsSecurity
info AuthorizeIOS Updating security db for developer access
info AuthorizeIOS Granting access to built-in simulator apps
info AuthorizeIOS The xcode directory is : /Applications/Xcode.app/Contents/Developer
info AuthorizeIOS Changing ownership to 'Rob' on directories:
ERR! AuthorizeIOS Encountered an issue changing user priveledges for iOS sim app dirs:
ERR! AuthorizeIOS Error was: Command 'chown -R Rob\:' exited with code 1```

**Comment by imurchie** [comment] 2017-11-14 19:47
Closing as duplicate of https://github.com/appium/appium/issues/9521

**Closed as completed by imurchie** 2017-11-14 19:47 UTC

**Comment by radamstx** [comment] 2017-11-14 19:51
Thanks for the explanation on the other ticket. Had followed outdated setup instructions.
